plugins {
    id 'java-library'
    id 'io.spring.dependency-management'
}

group = 'com.min'
version = '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:3.1.5"
    }
}

// bootJar 태스크 비활성화
jar {
    enabled = true
    archiveClassifier = '' // 일반 jar로 생성
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'com.fasterxml.jackson.core:jackson-databind'
}

test {
    useJUnitPlatform()
}